version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    hostname: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
        - "27017:27017"
    volumes:
        -  /data/db